
	TITLE	'RDDIAG - RD DIAGNOSTICS'
	EJECT
***	RDDIAG - RAMDISK DIAGNOSTICS
*
*       SMBAKER

	XTEXT	HOSDEF
	XTEXT	HOSEQU
	XTEXT   PGREG

	ORG	04000H		

ENTRY	LXI	HJ,INTRO
	SCALL	.PRINT
	CALL	PGINIT

	CALL	DETECT

	LXI	H,MNOMM
	LDA	DETNMMU
	ORA	A
	JNZ	NOMMU
	LXI	H,MHAVEMM
NOMMU	SCALL	.PRINT

	LXI	H,M512
	LDA	DET512
	ORA	A
	JNZ	Y512
	LXI	H,MNO512
Y512	SCALL	.PRINT

	LXI	H,MTINY
	LDA	DETTINY
	ORA	A
	JNZ	YTINY
	LXI	H,MNOTINY
YTINY	SCALL	.PRINT

	MVI	B,001H		B HOLDS BITMASK
	MVI	C,000H		C HOLDS BANK NUMBER

* PRINT OUT THE RESULTS FOR BANKS 0-7

DLOOP	LXI	HL,MBANK
	SCALL	.PRINT
	MOV	A,C
	CALL	PHEXA
	LXI	HL,MPRES
	LDA	DETRAML
	ANA	B
	JNZ	PRES
	LXI	HL,MFLASH
	LDA	DETFLSL
	ANA	B
	JNZ	PRES
	LXI	HL,MNPRES
PRES	SCALL	.PRINT
	MOV	A,B
	RLC
	MOV	B,A
	INR	C
	MOV	A,C
	CPI	08H		STOP AT DEVICE 7
	JNZ	DLOOP		KEEP LOOPING

* PRINT OUT THE RESULTS FOR BANKS 8-15

	MVI	B,001H		B HOLDS BITMASK
DLOOP1	LXI	HL,MBANK
	SCALL	.PRINT
	MOV	A,C
	CALL	PHEXA
	LXI	HL,MPRES
	LDA	DETRAMH
	ANA	B
	JNZ	PRES1
	LXI	HL,MFLASH
	LDA	DETFLSH
	ANA	B
	JNZ	PRES1
	LXI	HL,MNPRES
PRES1	SCALL	.PRINT
	MOV	A,B
	RLC
	MOV	B,A
	INR	C
	MOV	A,C
	CPI	10H		STOP AT DEVICE 15
	JNZ	DLOOP1		KEEP LOOPING

OUT	XRA	A
	SCALL	.EXIT

	XTEXT	PRHEX
	XTEXT	PGMAP
	XTEXT	DETECT

INTRO	DB	12Q,'RAMDISK DIAG UTILITY',212Q
MHAVEMM	DB	'MMU BOARD IS PRESENT',212Q
MNOMM	DB	'MMU BOARD IS NOT INSTALLED',212Q
MTINY	DB	'BANK0 IS ONLY 512K',212Q
MNOTINY	DB	'BANK0 HAS MORE THAN 512K',212Q
M512	DB	'BOARD IS SEBHC 512K BOARD',212Q
MNO512	DB	'BOARD IS SMBAKER 8MB BOARD',212Q
MBANK	DB	'BANK',' '+200Q
MNPRES	DB	' IS NOT PRESENT',212Q
MFLASH	DB	' IS FLASH',212Q
MPRES	DB	' IS PRESENT',212Q

	LON	G
	END	ENTRY
